unit Compiled;

interface

// <BUILDSTAMP:BEGINSTAMP>
const COMPILEDATE = '<BUILDSTAMP:COMPILEDATE>';
const COMPILETIME = '<BUILDSTAMP:COMPILETIME>';
const COMPILEDATETIME = '<BUILDSTAMP:COMPILEDATETIME>';

const COMPILEDATEUTC = '<BUILDSTAMP:COMPILEDATE-UTC>';
const COMPILETIMEUTC = '<BUILDSTAMP:COMPILETIME-UTC>';
const COMPILEDATETIMEUTC = '<BUILDSTAMP:COMPILEDATETIME-UTC>';
// <BUILDSTAMP:ENDSTAMP> 

implementation

end.
